package vn.lum1nous.trackify.error;

public enum ErrorCode {
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    BAD_REQUEST("BAD_REQUEST"),
    NOT_FOUND("NOT_FOUND"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),

    INVALID_TOKEN("INVALID_TOKEN"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),

    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    VERIFICATION_CODE_INVALID("VERIFICATION_CODE_INVALID"),
    VERIFICATION_CODE_EXPIRED("VERIFICATION_CODE_EXPIRED"),

    CV_INVALID("CV_INVALID"),
    CV_MISSING("CV_MISSING"),

    AVATAR_MISSING("AVATAR_MISSING"),
    AVATAR_INVALID("AVATAR_INVALID"),
    CLOUDINARY_UPLOAD_FAILED("CLOUDINARY_UPLOAD_FAILED"),

    CV_EXTRACT_FAILED("CV_EXTRACT_FAILED"),
    CV_UPLOAD_FAILED("CV_UPLOAD_FAILED");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
